# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

APPLY_FIXES: all
DISABLE_LINTERS:
  - SPELL_PROSELINT
  - REPOSITORY_GITLEAKS
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
JAVASCRIPT_DEFAULT_STYLE: prettier
JAVASCRIPT_ES_FILTER_REGEX_EXCLUDE: .eslintrc.js
TYPESCRIPT_DEFAULT_STYLE: prettier
TYPESCRIPT_ES_FILTER_REGEX_EXCLUDE: .eslintrc.js
BASH_EXEC_FILTER_REGEX_INCLUDE: .husky
BASH_EXEC_FILE_EXTENSIONS: ['']
BASH_SHELLCHECK_ARGUMENTS: -e SC1091
BASH_SHELLCHECK_FILTER_REGEX_INCLUDE: .husky
BASH_SHELLCHECK_FILE_EXTENSIONS: ['']
BASH_SHFMT_FILTER_REGEX_INCLUDE: .husky
BASH_SHFMT_FILE_EXTENSIONS: ['']
REPOSITORY_TRIVY_DISABLE_ERRORS: true
EDITORCONFIG_EDITORCONFIG_CHECKER_FILTER_REGEX_EXCLUDE: LICENSE