version: '3.7'

services:
  db:
    image: mysql:8.0.34-debian
    restart: always
    command: '--innodb_use_native_aio=0 --character-set-server=utf8 --collation-server=utf8_general_ci'
    cap_add: [SYS_NICE]
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
      - mysql:/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - '3306:3306'

  redis:
    image: 7.0-alpine3.18
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: yarn run start:dev
    env_file:
      - .env.docker
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app

volumes:
  mysql:
  redis:
