version: '3.7'

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webnc
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - '5432:5432'

  redis:
    image: redis/redis-stack:latest
    pull_policy: if_not_present
    restart: on-failure
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: yarn run start:dev
    env_file:
      - .env.docker
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - postgres

volumes:
  postgres:
  redis:
