name: Lint and test
on:
  pull_request:
    branches: ['master', 'develop']
  push:
    branches: ['master', 'develop']

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version

      - name: Cache pnpm dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm lint

      - name: Run build
        run: pnpm build

      - name: Sonar cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}

      # - name: Run test
      #   run: pnpm test
